"""Single-page, read-only V5 research dashboard. Preview port: 8899."""
from __future__ import annotations
from datetime import datetime
from http.server import BaseHTTPRequestHandler,ThreadingHTTPServer
import argparse,html,json
from pathlib import Path
from urllib.parse import urlparse
from .core import CHINA_TZ
from .sources import V5ReadOnlySources

CSS="""
:root{--bg:#071019;--panel:#0d1b26;--panel2:#102331;--line:#203847;--text:#edf5f7;--muted:#8da2ad;--cyan:#77d7ee;--green:#59d6a8;--red:#ff8194;--amber:#ffd166}*{box-sizing:border-box}html{background:var(--bg);-webkit-text-size-adjust:100%}body{margin:0;background:var(--bg);color:var(--text);font-family:"Microsoft YaHei",system-ui,sans-serif;line-height:1.55}.wrap{width:min(1160px,calc(100% - 32px));margin:0 auto;padding:24px 0 40px}.top{display:flex;justify-content:space-between;align-items:flex-start;gap:16px}.brand{font-size:25px;font-weight:850}.sub,.muted{color:var(--muted);font-size:13px}.lock{padding:6px 11px;border-radius:999px;background:#3a2028;color:#ff9bad;font-size:12px;white-space:nowrap}.hero,.card{background:var(--panel);border:1px solid var(--line);border-radius:16px}.hero{margin-top:18px;padding:22px}.eyebrow{color:var(--cyan);font-size:12px;font-weight:800}.hero h1{font-size:30px;line-height:1.3;margin:7px 0 14px}.action{border-left:4px solid var(--green);background:#081722;border-radius:8px;padding:13px}.facts{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-top:14px}.fact,.card{padding:17px}.fact{background:var(--panel2);border:1px solid var(--line);border-radius:13px}.value{font-size:23px;font-weight:800;margin-top:4px}.good{color:var(--green)}.bad{color:var(--red)}.warn{color:var(--amber)}.section-title{display:flex;align-items:end;justify-content:space-between;gap:12px;margin:26px 2px 10px}.section-title h2{font-size:20px;margin:0}.candidate{display:grid;grid-template-columns:75px minmax(0,1fr) 250px;gap:18px;margin-top:12px}.rank{font-size:28px;font-weight:900;color:var(--cyan)}.stock{font-size:21px;font-weight:800}.chips{display:flex;flex-wrap:wrap;gap:7px;margin:9px 0}.chip{font-size:12px;padding:4px 8px;border-radius:999px;background:#153043;color:#bfe9f5}.risk{color:#ff9bab}.plan{background:#091720;border-radius:10px;padding:12px}.plan b{color:var(--amber)}.empty{padding:28px;text-align:center}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:14px}.evidence{border-left:4px solid var(--amber)}.foot{margin-top:18px;color:#708590;font-size:12px}.meta{overflow-wrap:anywhere}@media(max-width:760px){.wrap{width:min(100% - 24px,680px);padding-top:15px}.top{align-items:center}.brand{font-size:22px}.sub{max-width:230px}.hero{padding:17px}.hero h1{font-size:24px}.facts{grid-template-columns:1fr 1fr}.candidate{grid-template-columns:52px minmax(0,1fr)}.candidate .plan{grid-column:1/-1}.grid2{grid-template-columns:1fr}.section-title{align-items:flex-start;flex-direction:column}.value{font-size:20px}}@media(max-width:420px){.facts{grid-template-columns:1fr}.candidate{display:block}.rank{font-size:17px;margin-bottom:5px}.lock{font-size:11px}.hero h1{font-size:22px}}
"""
def _money(value):return f"¥{float(value):,.2f}"
def _candidate(row,confirmed):
    reasons=" · ".join(row.get("reasons",[]));risks=" · ".join(row.get("risks",[]));ask=row.get("ask1")
    entry=(f"冻结卖一参考 {_money(ask)}；仅在 14:50–14:51:59 由本地模拟引擎按盘口和滑点成交" if confirmed and ask else "早盘仅观察，不允许买入；等待 14:49 冻结和 14:50 同母池确认")
    exit_rule="下一交易日 09:30 后按连续竞价买一和滑点模拟卖出；当前不能预知卖价"
    return f"<article class='card candidate'><div class='rank'>#{int(row['rank'])}</div><div><div class='stock'>{html.escape(str(row['name']))} <span class='muted'>{html.escape(str(row['code']))}</span></div><div class='chips'><span class='chip'>涨幅 {float(row['change_pct']):.2f}%</span><span class='chip'>相对分位 {float(row.get('score_percentile',0)):.0%}</span><span class='chip'>成交额 {float(row.get('amount',0))/1e8:.2f} 亿</span></div><div><b>入选理由：</b>{html.escape(reasons or '无')}</div><div class='risk'><b>主要风险：</b>{html.escape(risks or '隔夜风险')}</div><div class='muted meta'>行情 {html.escape(str(row.get('quote_time','无')))} · 来源 {html.escape(str(row.get('provider','无')))} · 快照 {html.escape(str(row.get('input_snapshot_id','无')))}</div></div><div class='plan'><b>买入规则</b><br>{html.escape(entry)}<br><br><b>卖出规则</b><br>{html.escape(exit_rule)}</div></article>"
def render(model,view="today"):
    value=model.to_dict();today=value["today"];c=value["candidates"];account=value["account"];validation=value["validation"];items=c["items"];confirmed=bool(today.get("confirmation_id"));quality=today["data_quality"];coverage=f"{today['coverage']*100:.1f}%" if today["coverage"] is not None else "无数据"
    candidates="".join(_candidate(row,confirmed) for row in items) if items else f"<div class='card empty'><div class='value'>当前没有推荐股票</div><p>{html.escape(str(c['empty_reason']))}</p><p class='muted'>空仓是有效决策；系统不会使用残缺行情、旧候选或代理价格凑数。</p></div>"
    ledger=account["ledger"];perf=account["performance"];positions=ledger.get("positions") or []
    return f"""<!doctype html><html lang='zh-CN'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>V5 A股隔夜研究</title><style>{CSS}</style></head><body><main class='wrap'><header class='top'><div><div class='brand'>V5 A股隔夜研究</div><div class='sub'>行情 → 母池 → 尾盘确认 → 严格模拟 → 绩效验证</div></div><span class='lock'>research_locked</span></header><section class='hero'><div class='eyebrow'>今天的结论</div><h1>{html.escape(today['action'])}</h1><div class='action'><b>现在该做什么</b><br>{'只观察系统冻结的候选与模拟结果，不进行实盘下单' if quality=='accepted' else '等待双源全市场行情通过严格质量门槛，不交易'}</div><div class='facts'><div class='fact'><div class='muted'>行情质量</div><div class='value {'good' if quality=='accepted' else 'bad'}'>{html.escape(quality)}</div></div><div class='fact'><div class='muted'>全市场覆盖</div><div class='value'>{coverage}</div></div><div class='fact'><div class='muted'>当前候选</div><div class='value'>{len(items)}</div></div><div class='fact'><div class='muted'>数据时间</div><div class='value' style='font-size:15px'>{html.escape(str(today.get('data_as_of') or '无'))}</div></div></div><p class='muted meta'>来源：{html.escape(str(today.get('source') or '无'))} · 快照：{html.escape(str(today.get('snapshot_id') or '无'))}</p></section><div class='section-title'><h2>今日推荐与执行规则</h2><span class='muted'>早盘候选不是买点；只有同日 14:50 确认后才进入本地模拟</span></div>{candidates}<div class='section-title'><h2>模拟账户与策略证据</h2><span class='muted'>验证系统是否有效，而不是展示漂亮胜率</span></div><div class='grid2'><section class='card'><div class='facts'><div><div class='muted'>可用现金</div><div class='value'>{_money(ledger.get('cash',100000))}</div></div><div><div class='muted'>当前持仓</div><div class='value'>{len(positions)}</div></div><div><div class='muted'>完整往返</div><div class='value'>{int(perf['trade_count'])}</div></div><div><div class='muted'>累计净收益</div><div class='value'>{_money(perf.get('net_pnl',0))}</div></div></div></section><section class='card evidence'><div class='eyebrow'>有效性结论</div><div class='value warn'>{'证据不足，不能证明策略有效' if validation['strategy_conclusion']=='INSUFFICIENT_EVIDENCE' else html.escape(validation['strategy_conclusion'])}</div><p>严格样本 {validation['strict_samples']} · 模拟往返 {validation['paper_round_trips']} · 模型 {html.escape(validation['model_status'])}</p><p class='muted'>排序分不是上涨概率；严格窗口、模拟账户和代理回测始终分开统计。</p></section></div><footer class='foot'>本系统只做本地研究与模拟，不连接券商，不构成投资建议。没有冻结盘口就不展示买价；次日开盘前不编造卖价。</footer></main></body></html>"""
class Handler(BaseHTTPRequestHandler):
    data_dir=Path("v5/data")
    def do_GET(self):
        path=urlparse(self.path).path;now=datetime.now(CHINA_TZ);model=V5ReadOnlySources(self.data_dir).build(now.date().isoformat(),as_of=now)
        if path=="/api/read-model":body=json.dumps(model.to_dict(),ensure_ascii=False).encode();kind="application/json; charset=utf-8"
        elif path in {"/","/today","/candidates","/account","/validation"}:body=render(model).encode();kind="text/html; charset=utf-8"
        else:self.send_error(404);return
        self.send_response(200);self.send_header("Content-Type",kind);self.send_header("Cache-Control","no-store");self.end_headers();self.wfile.write(body)
    def do_POST(self):self.send_error(405,"read only")
    def log_message(self,*args):pass
def main(port=8899,data_dir="v5/data"):Handler.data_dir=Path(data_dir);ThreadingHTTPServer(("127.0.0.1",port),Handler).serve_forever()
if __name__=="__main__":
    parser=argparse.ArgumentParser();parser.add_argument("--port",type=int,default=8899);parser.add_argument("--data-dir",default="v5/data");args=parser.parse_args();main(args.port,args.data_dir)
